In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('dataset\gen_output.csv')

In [4]:
df.head()

,row_id,active_mode,calculated_flow_rate_L_min,calculated_flow_rate_m3_h,hydraulic_power_kW,pump_head_m,pump_delta_pressure_bar,load_pressure_bar_g,target_pressure_error_bar,N_PUMP_IN_p,...,loss_C_B_LINE,loss_C_RETURN,Kv_V_DIR_PA,Kv_V_DIR_PB,Kv_V_DIR_AT,Kv_V_DIR_BT,Kv_V_RELIEF,solver_warning,contains_inf_or_nan,status
0,1_0,downstroke,18.67286,1.12037,5.69217,2168.69985,182.90205,170.125,0.0,-0.09244,...,2.15565,0.05443,0.33699,0.0,0.0,0.33325,0.0,no,no,ok
1,1_1,downstroke,21.05727,1.26344,6.67034,2253.60616,190.06281,175.466,0.0,-0.09427,...,2.43506,0.06166,0.35481,0.0,0.0,0.35928,0.0,no,no,ok
2,1_2,downstroke,24.37702,1.46262,7.94366,2318.31459,195.52014,178.479,0.0,-0.09689,...,2.82529,0.07183,0.37981,0.0,0.0,0.37450,0.0,no,no,ok
3,1_3,downstroke,25.64854,1.53891,8.67042,2404.97103,202.82850,184.994,0.0,-0.09796,...,2.98179,0.07592,0.39123,0.0,0.0,0.38728,0.0,no,no,ok
4,1_4,downstroke,27.56457,1.65387,9.58507,2473.86548,208.63886,190.071,0.0,-0.09954,...,3.20695,0.08184,0.41452,0.0,0.0,0.41913,0.0,no,no,ok

In [5]:
df.tail()

,row_id,active_mode,calculated_flow_rate_L_min,calculated_flow_rate_m3_h,hydraulic_power_kW,pump_head_m,pump_delta_pressure_bar,load_pressure_bar_g,target_pressure_error_bar,N_PUMP_IN_p,...,loss_C_B_LINE,loss_C_RETURN,Kv_V_DIR_PA,Kv_V_DIR_PB,Kv_V_DIR_AT,Kv_V_DIR_BT,Kv_V_RELIEF,solver_warning,contains_inf_or_nan,status
1450295,100000_11,upstroke,23.61200,1.41672,5.84960,1762.48385,148.64294,131.678,0.0,-0.08878,...,2.72562,0.03240,0.0,0.36275,0.36224,0.0,0.0,no,no,ok
1450296,100000_12,upstroke,25.37328,1.52240,6.47134,1814.47088,153.02738,135.029,0.0,-0.08964,...,3.07663,0.03505,0.0,0.38182,0.37562,0.0,0.0,no,no,ok
1450297,100000_13,upstroke,28.10257,1.68615,7.28382,1843.93405,155.51222,135.194,0.0,-0.09103,...,3.65510,0.03920,0.0,0.40106,0.39853,0.0,0.0,no,no,ok
1450298,100000_14,upstroke,31.58472,1.89508,8.46420,1906.51863,160.79042,136.536,0.0,-0.09294,...,4.45772,0.04472,0.0,0.41379,0.41609,0.0,0.0,no,no,ok
1450299,100000_15,upstroke,32.52519,1.95151,8.99805,1968.16033,165.98911,140.943,0.0,-0.09347,...,4.68548,0.07688,0.0,0.42056,0.42165,0.0,0.0,no,no,ok

In [6]:
df.describe()

,calculated_flow_rate_L_min,calculated_flow_rate_m3_h,hydraulic_power_kW,pump_head_m,pump_delta_pressure_bar,load_pressure_bar_g,target_pressure_error_bar,N_PUMP_IN_p,N_PUMP_OUT_p,N_VALVE_P_p,...,loss_C_SUCTION,loss_C_PRESSURE,loss_C_A_LINE,loss_C_B_LINE,loss_C_RETURN,Kv_V_DIR_PA,Kv_V_DIR_PB,Kv_V_DIR_AT,Kv_V_DIR_BT,Kv_V_RELIEF
count,1.450300e+06,1.450300e+06,1.450300e+06,1.450300e+06,1.450300e+06,1.450300e+06,1.450300e+06,1.450300e+06,1.450300e+06,1.450300e+06,...,1.450300e+06,1.450300e+06,1.450300e+06,1.450300e+06,1.450300e+06,1.450300e+06,1.450300e+06,1.450300e+06,1.450300e+06,1450300.0
mean,2.343347e+01,1.406008e+00,7.091944e+00,1.921308e+03,1.620377e+02,1.661427e+02,2.690903e+00,-9.293685e-02,1.619448e+02,1.606712e+02,...,2.114344e-02,1.273562e+00,3.291479e+00,2.983866e+00,7.138970e-02,1.782611e-01,1.518032e-01,1.579552e-01,1.837428e-01,0.0
std,1.008659e+01,6.051954e-01,3.337816e+00,7.247384e+02,6.112240e+01,3.305722e+01,8.467329e+00,3.883807e-02,6.109364e+01,6.069095e+01,...,2.363170e-02,1.280350e+00,1.756106e+00,1.592151e+00,3.243219e-02,1.888143e-01,1.857019e-01,1.893201e-01,1.916545e-01,0.0
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.054758e+01,0.000000e+00,-3.960700e-01,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
25%,2.001618e+01,1.200970e+00,5.479460e+00,1.767604e+03,1.490747e+02,1.346530e+02,0.000000e+00,-1.033500e-01,1.489720e+02,1.476675e+02,...,1.349000e-02,8.023000e-01,2.628167e+00,2.381518e+00,5.829000e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
50%,2.515398e+01,1.509240e+00,7.416880e+00,2.053674e+03,1.732011e+02,1.722788e+02,0.000000e+00,-9.823000e-02,1.731005e+02,1.713997e+02,...,1.811000e-02,1.094070e+00,3.371975e+00,3.056555e+00,7.583000e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
75%,3.013032e+01,1.807820e+00,9.325175e+00,2.397265e+03,2.021786e+02,1.902850e+02,0.000000e+00,-9.361000e-02,2.020774e+02,2.007626e+02,...,2.323000e-02,1.418680e+00,4.106940e+00,3.724123e+00,9.330000e-02,3.736100e-01,3.644900e-01,3.694700e-01,3.780000e-01,0.0
max,5.216317e+01,3.129790e+00,1.759812e+01,3.125803e+03,2.636214e+02,2.532950e+02,7.405872e+01,0.000000e+00,2.635361e+02,2.632495e+02,...,3.159500e-01,1.670966e+01,1.500848e+01,1.360353e+01,1.780300e-01,4.483100e-01,4.443200e-01,4.435100e-01,4.439400e-01,0.0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450300 entries, 0 to 1450299
Data columns (total 38 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   row_id                      1450300 non-null  object
 1   active_mode                 1450300 non-null  object
 2   calculated_flow_rate_L_min  1450300 non-null  float64
 3   calculated_flow_rate_m3_h   1450300 non-null  float64
 4   hydraulic_power_kW          1450300 non-null  float64
 5   pump_head_m                 1450300 non-null  float64
 6   pump_delta_pressure_bar     1450300 non-null  float64
 7   load_pressure_bar_g         1450300 non-null  float64
 8   target_pressure_error_bar   1450300 non-null  float64
 9   N_PUMP_IN_p                 1450300 non-null  float64
 10  N_PUMP_OUT_p                1450300 non-null  float64
 11  N_VALVE_P_p                 1450300 non-null  float64
 12  N_VALVE_A_p                 1450300 non-null  float64
 13  N_VALVE_B_p                 1450300 non-null  float64
 14  N_VALVE_T_p                 1450300 non-null  float64
 15  N_CYL_CAP_p                 1450300 non-null  float64
 16  N_CYL_ROD_p                 1450300 non-null  float64
 17  vel_C_SUCTION               1450300 non-null  float64
 18  vel_C_PRESSURE              1450300 non-null  float64
 19  vel_C_A_LINE                1450300 non-null  float64
 20  vel_C_B_LINE                1450300 non-null  float64
 21  vel_C_RETURN                1450300 non-null  float64
 22  vel_V_RELIEF                1450300 non-null  float64
 23  vel_C_RELIEF                1450300 non-null  float64
 24  max_active_velocity         1450300 non-null  float64
 25  loss_C_SUCTION              1450300 non-null  float64
 26  loss_C_PRESSURE             1450300 non-null  float64
 27  loss_C_A_LINE               1450300 non-null  float64
 28  loss_C_B_LINE               1450300 non-null  float64
 29  loss_C_RETURN               1450300 non-null  float64
 30  Kv_V_DIR_PA                 1450300 non-null  float64
 31  Kv_V_DIR_PB                 1450300 non-null  float64
 32  Kv_V_DIR_AT                 1450300 non-null  float64
 33  Kv_V_DIR_BT                 1450300 non-null  float64
 34  Kv_V_RELIEF                 1450300 non-null  float64
 35  solver_warning              1450300 non-null  object
 36  contains_inf_or_nan         1450300 non-null  object
 37  status                      1450300 non-null  object
dtypes: float64(33), object(5)
memory usage: 420.5+ MB

In [8]:
df

,row_id,active_mode,calculated_flow_rate_L_min,calculated_flow_rate_m3_h,hydraulic_power_kW,pump_head_m,pump_delta_pressure_bar,load_pressure_bar_g,target_pressure_error_bar,N_PUMP_IN_p,...,loss_C_B_LINE,loss_C_RETURN,Kv_V_DIR_PA,Kv_V_DIR_PB,Kv_V_DIR_AT,Kv_V_DIR_BT,Kv_V_RELIEF,solver_warning,contains_inf_or_nan,status
0,1_0,downstroke,18.67286,1.12037,5.69217,2168.69985,182.90205,170.125,0.0,-0.09244,...,2.15565,0.05443,0.33699,0.00000,0.00000,0.33325,0.0,no,no,ok
1,1_1,downstroke,21.05727,1.26344,6.67034,2253.60616,190.06281,175.466,0.0,-0.09427,...,2.43506,0.06166,0.35481,0.00000,0.00000,0.35928,0.0,no,no,ok
2,1_2,downstroke,24.37702,1.46262,7.94366,2318.31459,195.52014,178.479,0.0,-0.09689,...,2.82529,0.07183,0.37981,0.00000,0.00000,0.37450,0.0,no,no,ok
3,1_3,downstroke,25.64854,1.53891,8.67042,2404.97103,202.82850,184.994,0.0,-0.09796,...,2.98179,0.07592,0.39123,0.00000,0.00000,0.38728,0.0,no,no,ok
4,1_4,downstroke,27.56457,1.65387,9.58507,2473.86548,208.63886,190.071,0.0,-0.09954,...,3.20695,0.08184,0.41452,0.00000,0.00000,0.41913,0.0,no,no,ok
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1450295,100000_11,upstroke,23.61200,1.41672,5.84960,1762.48385,148.64294,131.678,0.0,-0.08878,...,2.72562,0.03240,0.00000,0.36275,0.36224,0.00000,0.0,no,no,ok
1450296,100000_12,upstroke,25.37328,1.52240,6.47134,1814.47088,153.02738,135.029,0.0,-0.08964,...,3.07663,0.03505,0.00000,0.38182,0.37562,0.00000,0.0,no,no,ok
1450297,100000_13,upstroke,28.10257,1.68615,7.28382,1843.93405,155.51222,135.194,0.0,-0.09103,...,3.65510,0.03920,0.00000,0.40106,0.39853,0.00000,0.0,no,no,ok
1450298,100000_14,upstroke,31.58472,1.89508,8.46420,1906.51863,160.79042,136.536,0.0,-0.09294,...,4.45772,0.04472,0.00000,0.41379,0.41609,0.00000,0.0,no,no,ok
1450299,100000_15,upstroke,32.52519,1.95151,8.99805,1968.16033,165.98911,140.943,0.0,-0.09347,...,4.68548,0.07688,0.00000,0.42056,0.42165,0.00000,0.0,no,no,ok

In [3]:
df2 = pd.read_csv('dataset/final_training_dataset.csv')
df2

C:\Users\vnm19\AppData\Local\Temp\ipykernel_23920\1170970244.py:1: DtypeWarning: Columns (38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('dataset/final_training_dataset.csv')

,cycle_id,cycle_second,cycle_phase,target_chamber,temperature_c,pump_rpm,valve_cmd_pa,valve_pos_pa,valve_cmd_pb,valve_pos_pb,...,gt_loss_C_A_LINE,gt_loss_C_B_LINE,gt_loss_C_RETURN,gt_leak_mode,gt_fault_location,fault_class,severity_level,fault_severity,onset_type,is_anomaly
0,1,0,downstroke,cap,43.714,1601,67.398,67.398,0.000,0.000,...,2.3791,2.1557,0.05443,NaN,NaN,normal,none,0.0,normal,0
1,1,1,downstroke,cap,43.724,1642,70.963,70.963,0.000,0.000,...,2.6870,2.4351,0.06166,NaN,NaN,normal,none,0.0,normal,0
2,1,2,downstroke,cap,43.743,1682,75.963,75.963,0.000,0.000,...,3.1168,2.8253,0.07183,NaN,NaN,normal,none,0.0,normal,0
3,1,3,downstroke,cap,43.660,1718,78.246,78.246,0.000,0.000,...,3.2891,2.9818,0.07592,NaN,NaN,normal,none,0.0,normal,0
4,1,4,downstroke,cap,43.693,1752,82.904,82.904,0.000,0.000,...,3.5370,3.2069,0.08184,NaN,NaN,normal,none,0.0,normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1450295,100000,11,upstroke,rod,76.602,1481,0.000,0.000,72.551,72.551,...,3.0070,2.7256,0.03240,NaN,Fluid,overheat,severe,1.0,abrupt,1
1450296,100000,12,upstroke,rod,76.638,1512,0.000,0.000,76.365,76.365,...,3.3941,3.0766,0.03505,NaN,Fluid,overheat,severe,1.0,abrupt,1
1450297,100000,13,upstroke,rod,76.720,1542,0.000,0.000,80.212,80.212,...,4.0320,3.6551,0.03920,NaN,Fluid,overheat,severe,1.0,abrupt,1
1450298,100000,14,upstroke,rod,76.703,1591,0.000,0.000,82.758,82.758,...,4.9170,4.4577,0.04472,NaN,Fluid,overheat,severe,1.0,abrupt,1
1450299,100000,15,upstroke,rod,76.718,1620,0.000,0.000,84.112,84.112,...,5.1681,4.6855,0.07688,NaN,Fluid,overheat,severe,1.0,abrupt,1

In [4]:
print(df2.columns[38])
print(df2.columns[39])

print(df2.iloc[:, 38].value_counts(dropna=False).head(20))
print(df2.iloc[:, 39].value_counts(dropna=False).head(20))

gt_leak_mode
gt_fault_location
gt_leak_mode
NaN               1145944
internal           101527
external           101454
valve_internal     101375
Name: count, dtype: int64
gt_fault_location
NaN              435352
V_RELIEF         203092
V_DIR_PA         118888
C_SUCTION        101575
PUMP_01          101552
N_CYL_CAP-ROD    101527
Fluid            101449
C_PRESSURE       101394
V_DIR_PB          84017
N_VALVE_A         34589
N_VALVE_P         33529
N_CYL_CAP         33336
Name: count, dtype: int64